[package]
name = "subsonic"
version = "0.1.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
subtle = "*"
num_cpus = "*"
crossbeam-utils = "*"

[dev-dependencies]
hex-literal = "0.1"
rand_core = "0.5"
rand_xorshift = "0.2"
sha2 = "0.8"
